---
kind: pipeline
type: docker
name: lint

steps:
  - name: Lint Dockerfile
    image: hadolint/hadolint:latest-debian
    pull: if-not-exists
    commands:
      - hadolint --version
      - hadolint Dockerfile
    when:
      status:
        - failure
        - success

  - name: Lint entrypoint scripts
    image: koalaman/shellcheck-alpine
    pull: if-not-exists
    commands:
      - shellcheck entrypoint.sh
    when:
      status:
        - failure
        - success

trigger:
  event:
    - pull_request
    - push
  ref:
    exclude:
      - refs/heads/renovate/*

---
kind: pipeline
type: docker
name: test

steps:
  - name: docker
    image: plugins/docker
    pull: if-not-exists
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password_ro
      repo: mwalbeck/twitchlite
      dry_run: true

trigger:
  event:
    - pull_request

depends_on:
  - lint

---
kind: pipeline
type: docker
name: build and publish

steps:
  - name: determine tags
    image: mwalbeck/determine-docker-tags
    pull: if-not-exists
    environment:
      CUSTOM_TAGS: latest

  - name: docker
    image: plugins/docker
    pull: if-not-exists
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: mwalbeck/twitchlite
      tags:
        - "latest"
  
  - name: notify
    image: plugins/matrix
    pull: if-not-exists
    settings:
      homeserver: https://matrix.mwalbeck.org
      roomid:
        from_secret: matrix_roomid
      username:
        from_secret: matrix_username
      password:
        from_secret: matrix_password
    when:
      status:
        - success
        - failure

trigger:
  branch:
    - master
  event:
    - push

depends_on:
  - lint

---
kind: signature
hmac: 16b2523d00e48b4b9189e259485e74330c3c6a2013bbeb4d5587dcfa9dec4a8a

...
