---
kind: pipeline
type: docker
name: test

steps:
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: mwalbeck/twitchlite
      dry_run: true

trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: build and publish

steps:
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: mwalbeck/twitchlite
      tags:
        - "latest"
  
  - name: notify
    image: plugins/matrix
    settings:
      homeserver: https://matrix.mwalbeck.org
      roomid:
        from_secret: matrix_roomid
      username:
        from_secret: matrix_username
      password:
        from_secret: matrix_password
    when:
      status:
        - success
        - failure

trigger:
  branch:
    - master
  event:
    - push
